# dubbo配置
dubbo:
  application:
    name: consumer
    qos-enable: true
    qos-port: 44444
    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://xxxx:8848

